language: objective-c
osx_image: xcode8.3
xcode_project: CI Test.xcodeproj
xcode_scheme: CI Test
xcode_sdk: iphonesimulator10.3
env:
  global:
  - APP_NAME="CI Test"
  - 'DEVELOPER_NAME="iPhone Distribution: Alex Louey (5B403HE559)"'
  - PROFILE_NAME="IOS_CI_Test_Ad_Hoc"
  - secure: ANmiBxkQDO7RPS3KMY6PBXRB+0ANC5waum7Z+f2HaBmPtsiJBmJRkaIg4z5Wrzz6a5Fc7wLGr5AcmdjEYFFHLVd9Rhx53peVuypnqZuWMRgYY8qr6sSJFICoNMmO973TmgRDRe3hsC/5ayLOpXtX/jbKvlBoiUNWmN9QIWbFsSKeRvyP7LP0gjb7shhyZ8HfbdFrjRQXkpieVO1LALo7QdLz02hD7zRiLc9uBhgfBovqUF/3CSnW1npMS+lHj4/iy25dGM99ZESDhSPyU/BkJTDwqiErILSGujO2hsCjmx+r4nWJx6Q2Opx/VufbXt8zkRoKwe72ZcyGkRiIYdORLRq7nBPcRyrOcNwThUF7D7ESmSrs8eTFP2BND/LUNmNwq/X9RPsvfT3Fpa3+oK8VzX+nsuNtSdFn7baXjzji42icToNhIkfB29NE/cCWY9sSDGHrz/fpqVSrmqh7GVke6dt5ZbMyjLu5pmcb+8ppM1LQOUo2RWlRK18Woh8CC4SIA7NsbhM4xlcUb8Etn3Q/2W+YbXWQ072PIrC6ea3+NoGuRGRvqC5mFWoiALYX9UbZ+Vo8Z29NzA92ZhCfeNmZgyEcTPwO9I30Znj8lfaOi67v8EduallcJwK+Xne4yM8Qv1FaPjPDoSqH3qWCEunygAqMK8B+8/XTAatMFHFEpws=
  - secure: DTgYSJ2F0dKkkYibUfRbcdxuj7FPrPpHQ3vlVmJBPR2yBDkf6sJdmG3ZfmToNNJoBcigrY6ksWAPLJQTNzzGJM3Xa7DHkc7WOpnmesCwFA4bmzg9Lesa5Kw/iRontWrpBkTfFuMuBIf0XyRm/usg/rVWAlvr+LAwOlMsbJ/3oXNVdVrosWaqVKXPE208E9Te0kkqpHi75HsRWi8u/oY4eDoPDy4pt0GkE5gvuop5WaW32ch9Y7+GDahV5lXmgR7reLz3OfTmXhefWmRu0fT5caDzS0evG7ogsXMT2h87DBJ2rxOA0/jjzm+UPYUH1RkVaf7KSkwZC7uk3Yh/mys8ADBxUiBRBUsWfChuvEcKGeNp1R6ZLiK31/Fsr9oMFozi3OdhpnNx5eIolyizZ/pYbHwcJ2qS9Iq+3atRJanHkeDUbTcjsvd7vAZPWEH7hXy7v5ZDwi4NOH8VD0ePh8BKko+rcuAL9L9AgX2eF406/Ur+JuogCKdBw0ca/4rOuanXupQStG90aak0Ou6/P1gJ8WrfYpfjMk6o4Ee0g0cdIua+qgNsO71la5VvojzXSaxyj9BdFTaJ2DHvfS+oct6yl9LcbJ8HYReTyf/5m0PM565xOwJBgZLH8XeLvZcJPOcBQmESbxAo99eSNn9jxM8XNfWptEtooaV7+Bc6lEDmiUU=

before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/IOS_CI_Test_Ad_Hoc.mobileprovision.enc -d -a -out scripts/profile/IOS_CI_Test_Ad_Hoc.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh

script:
- gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
- rvm get stable
- rvm cleanup all
- xcodebuild test -project "CI Test.xcodeproj" -scheme "CI Test" -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3.1' -sdk iphonesimulator10.3 ONLY_ACTIVE_ARCH=NO
- xcodebuild -project "CI Test.xcodeproj" -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO

after_success:
- ./scripts/sign-and-upload.sh

after_script:
- ./scripts/remove-key.sh
