language: objective-c
osx_image: xcode8.3
xcode_project: "CI Test.xcodeproj"
xcode_scheme: "CI Test"
xcode_sdk: iphonesimulator10.3
script: gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 && rvm get stable && rvm cleanup all