language: objective-c
xcode_project: "CI Test.xcodeproj"
xcode_scheme: "CI Test"
script: rvm get stable && xcodebuild -destination "platform=IOS Simulator,name=iPhone 6" -scheme "CI Test" build && xcodebuild -destination "platform=IOS Simulator,name=iPhone 6" -scheme "CI Test" test